config/routes.rb
Rails.application.routes.draw do

  root "apples#index"
  resources :apples

  post "/apples/:id/yum" => "apples#yum", :as => "apple_yum"
  post "/apples/:id/yuck" => "apples#yuck", :as => "apple_yuck"

end

app/models/apple.rb
class Apple < ActiveRecord::Base
  self.inheritance_column = nil

  validates :type, :presence => true

  def difference
    self.yums.to_i - self.yucks.to_i
  end

end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController

  def index
    @apples = Apple.all
  end

  def create
    @apple = Apple.new(apple_params)
    @apple.save
    redirect_to apples_path
  end

  def show
    @apple = Apple.find(params[:id])
  end

  def edit
    @apple = Apple.find(params[:id])
  end

  def update
    @apple = Apple.find(params[:id])
    @apple.update(apple_params)

    redirect_to :back
  end

  def yum
    @apple = Apple.find(params[:id])
    yums = @apple.yums.to_i
    @apple.update(:yums => yums + 1)

    redirect_to :back
  end

  def yuck
    @apple = Apple.find(params[:id])
    yucks = @apple.yucks.to_i
    @apple.update(:yucks => yucks + 1)

    redirect_to :back
  end

  private

  def apple_params
    params.require(:apple).permit(:type, :color, :description, :yums, :yucks)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apples/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Yum? or Yuck?</h3>
    <h5>click to rate your favorite apples</h5>
  </div>
  <div class="panel-body">
    <!-- Table -->
    <% sorted_list = @apples.sort_by { |a| a.difference }.reverse %>
    <% sorted_list.each do |apple| %>
    <table class="apples-index">
      <tr>
        <td class="table-items"><h5><%= apple.yums.to_i %></h5></td>
        <td class="table-items"><%= button_to "yum", apple_yum_path(:id => apple.id), {class: "btn btn-sm btn-default"} %></td>
        <td class="table-items"><h3><%= link_to "#{apple.type}", apple_path(:id => apple.id) %></h3></td>
        <td class="table-items"><%= button_to "yuck", apple_yuck_path(:id => apple.id), {class: "btn btn-sm btn-default"} %></td>
        <td class="table-items"><h5><%= apple.yucks.to_i %></h5></td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

<div class="new-apple">
  <h4>don't see your favorite apple?  add it here!</h4>
  <%= form_for Apple.new do |f| %>
    <%= f.text_field :type, :value => "type"  %>
    <%= f.text_field :description, :value => "one-word description" %>
    <br class="clearfix" />
    <br class="clearfix" />
  <%= f.submit "add a new apple", {class: "btn btn-sm btn-success"} %>
</div>
<% end %>

<div class="hello">
  <p>do you like apples?  i know i do!  biting into a crisp, juicy apple is one of life's greatest joys, and i'm always on the lookout for a better bite.  use this app to track what you like and don't like...and to see what others have to say on the subject as well.  thanks for stopping by!</p><br>
  <p>lauren</p>
</div>

app/views/apples/show.html.erb
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="jqcloud.css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
    <script type="text/javascript" src="jqcloud-1.0.4.js"></script>
    <script type="text/javascript">
      /*!
       * Create an array of word objects, each representing a word in the cloud
       */
      var word_array = [
          {text: "Lorem", weight: 15},
          {text: "Ipsum", weight: 9, link: "http://jquery.com/"},
          {text: "Dolor", weight: 6, html: {title: "I can haz any html attribute"}},
          {text: "Sit", weight: 7},
          {text: "Amet", weight: 5}
          // ...as many words as you want
      ];

      $(function() {
        // When DOM is ready, select the container element and call the jQCloud method, passing the array of words as the first argument.
        $("#cloud").jQCloud(word_array);
      });
    </script>
  </head>
  <body>
    <div class="show" id="cloud" style="width: 550px; height: 350px;">
      <h4><%= @apple.type %></h4>
      <ul>
        <%= @apple.description %>
      </ul>
      <p>how would you describe this apple?</p>
        <div>
        <%= form_for @apple do |f| %>
          <%= f.text_field :description, :value => nil %>
          <br class="clearfix" />
          <br class="clearfix" />
        <%= f.submit "add your description", :class => "btn btn-sm btn-success" %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Honeycrisp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet"> -->

  <!-- // <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script> -->
</head>

<body>
  <div class="page-header">
    <h1><small style="color:black">you like apples?</small></br><%= link_to "how 'bout them apples?", root_path %></h1>
  </div>

<%= yield %>
<!--
  <div class="footer">
    <p>made by lauren</p>
  </div> -->

</body>
</html>